// let's import a selection of icons, so we can reduce bundle size
import {
  FaTimes,
  FaBars,
  FaBriefcase,
  FaHome,
  FaUsers,
  // FaClipboardCheck,
  FaPaperPlane,
  FaInfoCircle,
  FaUser,
  FaSignOutAlt,
  FaSignInAlt,
  FaUserPlus,
  FaAngleLeft,
  FaAngleRight,
  FaAngleDoubleLeft,
  FaAngleDoubleRight,
  FaArrowLeft,
  FaRegTimesCircle,
  FaCalendarAlt,
  FaCalendarCheck,
  FaCalendarTimes,
  FaCheckCircle,
  FaTimesCircle,
  FaQuestionCircle,
  FaEyeSlash,
  FaEye,
} from 'react-icons/fa';

export {
  FaTimes,
  FaBars,
  FaBriefcase,
  FaHome,
  FaUsers,
  // FaClipboardCheck,
  FaPaperPlane,
  FaInfoCircle,
  FaUser,
  FaSignOutAlt,
  FaSignInAlt,
  FaUserPlus,
  FaAngleLeft,
  FaAngleRight,
  FaAngleDoubleLeft,
  FaAngleDoubleRight,
  FaArrowLeft,
  FaRegTimesCircle,
  FaCalendarAlt,
  FaCalendarCheck,
  FaCalendarTimes,
  FaCheckCircle,
  FaTimesCircle,
  FaQuestionCircle,
  FaEyeSlash,
  FaEye,
};
