// let's import a selection of icons, so we can reduce bundle size
import {
  FaTimes,
  FaBars,
  FaBriefcase,
  FaHome,
  FaUsers,
  // FaClipboardCheck,
  FaPaperPlane,
  FaInfoCircle,
  FaUser,
  FaSignOutAlt,
  FaSignInAlt,
  FaUserPlus,
  FaAngleLeft,
  FaAngleRight,
  FaAngleDoubleLeft,
  FaAngleDoubleRight,
  FaArrowLeft,
  FaRegTimesCircle,
  FaCalendarAlt,
  FaCalendarCheck,
  FaCalendarTimes,
  FaCheckCircle,
  FaTimesCircle,
  FaQuestionCircle,
  FaEyeSlash,
  FaEye,
  FaExclamationTriangle,
  FaRegCalendarAlt,
  FaChartBar,
  FaTools,
  FaArrowAltCircleRight,
  FaUserCircle,
} from 'react-icons/fa';

import { FaClipboardQuestion, FaRocket } from 'react-icons/fa6';

export {
  FaTimes,
  FaBars,
  FaBriefcase,
  FaHome,
  FaUsers,
  // FaClipboardCheck,
  FaPaperPlane,
  FaInfoCircle,
  FaUser,
  FaSignOutAlt,
  FaSignInAlt,
  FaUserPlus,
  FaAngleLeft,
  FaAngleRight,
  FaAngleDoubleLeft,
  FaAngleDoubleRight,
  FaArrowLeft,
  FaRegTimesCircle,
  FaCalendarAlt,
  FaCalendarCheck,
  FaCalendarTimes,
  FaCheckCircle,
  FaTimesCircle,
  FaQuestionCircle,
  FaEyeSlash,
  FaEye,
  FaClipboardQuestion,
  FaRocket,
  FaExclamationTriangle,
  FaRegCalendarAlt,
  FaChartBar,
  FaTools,
  FaArrowAltCircleRight,
  FaUserCircle,
};
