// user
export const SET_USER = 'SET_USER';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const SET_LOADING = 'SET_LOADING';
export const SET_HAS_PASSWORD = 'SET_HAS_PASSWORD';

// loading
export const LOADING_START = 'LOADING_START';
export const LOADING_STOP = 'LOADING_STOP';

// company
export const SET_HOLIDAY_ENTITLEMENT = 'SET_HOLIDAY_ENTITLEMENT';
export const SET_WORKDAYS_OF_THE_WEEK = 'SET_WORKDAYS_OF_THE_WEEK';
export const SET_REGIONS_AND_YEARS_LOADED = 'SET_REGIONS_AND_YEARS_LOADED';
export const SET_REGIONS_AND_YEARS = 'SET_REGIONS_AND_YEARS';
