// user
export const SET_USER = 'SET_USER';
export const SET_USER_COUNT = 'SET_USER_COUNT';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const SET_LOADING = 'SET_LOADING';
export const SET_HAS_PASSWORD = 'SET_HAS_PASSWORD';

// loading
export const LOADING_START = 'LOADING_START';
export const LOADING_STOP = 'LOADING_STOP';

// company
export const SET_HOLIDAY_ENTITLEMENT = 'SET_HOLIDAY_ENTITLEMENT';
export const SET_WORKDAYS_OF_THE_WEEK = 'SET_WORKDAYS_OF_THE_WEEK';
export const SET_BANK_HOLIDAY_REGION = 'SET_BANK_HOLIDAY_REGION';
export const SET_IMPORTED_REGIONS = 'SET_IMPORTED_REGIONS';
export const SET_IMPORTED_YEARS = 'SET_IMPORTED_YEARS';

// requests
export const SET_OWN_REQUEST_COUNT = 'SET_OWN_REQUEST_COUNT';
export const SET_OWN_APPROVED_LEAVES_COUNT = 'SET_OWN_APPROVED_LEAVES_COUNT';
export const SET_OWN_REJECTED_LEAVES_COUNT = 'SET_OWN_REJECTED_LEAVES_COUNT';
export const SET_MANAGABLE_REQUEST_COUNT = 'SET_MANAGABLE_REQUEST_COUNT';
export const SET_MANAGABLE_APPROVED_LEAVES_COUNT =
  'SET_MANAGABLE_APPROVED_LEAVES_COUNT';
export const SET_MANAGABLE_REJECTED_LEAVES_COUNT =
  'SET_MANAGABLE_REJECTED_LEAVES_COUNT';
